image: "hub.ricebook.net/base/centos:onbuild-eru-core-2017.07.26"
stages:
  - test
  - build
  - rpm
test:
  stage: test
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/core"
    - make test
build:
  stage: build
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/core"
    - make build
    - cp -r eru-core $CI_PROJECT_DIR
  artifacts:
    paths:
      - "eru-core"
    expire_in: 1 week
rpm:
  stage: rpm
  script:
    - "./make-rpm"
  dependencies:
    - "build"
  artifacts:
    paths:
      - "eru-core*.rpm"
    expire_in: 1 week
