version: 2
jobs:
  build:
    docker:
      - image: projecteru2/footstone:latest
    working_directory: /.go/src/github.com/projecteru2/core
    steps:
      - checkout
      - run: make test
      - run: make build
      - run: ./make-release
      - run:
          name: Create artifacts
          command: |
            mkdir -p /tmp/release
            cp -r eru*.rpm /tmp/release
            cp -r eru*.deb /tmp/release
            cp -r eru-core /tmp/release/eru-core_linux_x86_64
            cp -r core.yaml.sample /tmp/release
            cp -r eru-core.service /tmp/release
      - run:
          name: Check files
          command: |
            rpm -qlp eru*.rpm
            dpkg -c eru*.deb
      - store_artifacts:
          path: /tmp/release
          destination: Release

