name: docker-image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository }} 
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag

      - name: Build and push image
        if: ${{ steps.meta.outputs.tags != '' }}
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: "[debug version] Build and push image"
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          build_args: |
            KEEP_SYMBOL=1
          tags: |
            ${{ github.repository }}:${{ github.sha }}-debug
            ghcr.io/${{ github.repository }}:${{ github.sha }}-debug
